# Generated by Django 2.1 on 2020-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200724_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, default='/media/default-user.jpg', null=True, upload_to='media/'),
        ),
    ]
